---
- name: Create docker container for jellyseerr
  docker_container:
    name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/jellyseerr/config:/app/config"
    ports:
      - '5059:5055'
    networks:
      - name: services

