---
- hosts: airfryer
  become: true
  vars_files:
    - group_vars/all/private.yml
    - group_vars/all/main.yml
  roles:
    - role: chriswayg.msmtp-mailer
    - role: system/essential
    - role: system/docker
    - role: system/monitoring
    - role: jahrik.yay
    - role: geerlingguy.ntp
    - role: security/fail2ban
    - role: geerlingguy.security
    # - role: security/iptables
    - role: network/avahi
    - role: network/duckdns
    - role: filesystem/mergerfs
    - role: filesystem/essential
    - role: filesystem/samba
    - role: services/filebrowser
    - role: services/plex
    - role: services/deluge
    - role: services/radarr
    - role: services/sonarr
    - role: services/lidarr
    - role: services/bazarr
    - role: services/prowlarr
    - role: services/ombi
    - role: services/authelia
    - role: services/raneto
    - role: services/watchtower
    - role: network/swag
  tasks:
    - meta: noop
