---
- hosts: airfryer
  become: true
  vars_files:
    - group_vars/all/private.yml
    - group_vars/all/main.yml
  roles:
    - role: system/essential
    - role: system/monitoring
    # - role: chriswayg.msmtp-mailer
    - role: geerlingguy.ntp
    - role: security/fail2ban
    - role: geerlingguy.security
    - role: security/iptables
    - role: docker
    - role: network/duckdns
  tasks:
    - meta: noop
