---
- name: Create docker container for Prowlarr
  docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/prowlarr/config:/config"
    ports:
      - '9696:9696'
    networks:
      - name: services

