---
- name: Create docker container for Bazarr
  docker_container:
    name: bazarr
    image: lscr.io/linuxserver/bazarr
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/bazarr/config:/config"
      - "{{ mergerfs_directory }}/media/Movies:/movies"
      - "{{ mergerfs_directory }}/media/Series:/tv"
    ports:
      - '6767:6767'
    networks:
      - name: services
