---
- name: Create docker container for Plex
  docker_container:
    hostname: 'airfryer-plex'
    name: plex
    image: lscr.io/linuxserver/plex
    restart_policy: 'unless-stopped'
    pull: yes
    network_mode: host
    env:
      PUID: '1000'
      PGID: '1000'
      VERSION: '1.24.0'
      PLEX_CLAIM: "{{ plex_claim }}"
    volumes: "{{ plex_container_volumes }}"