---
- name: Create docker container for Plex
  docker_container:
    hostname: 'airfryer-plex'
    name: plex
    image: lscr.io/linuxserver/plex
    restart_policy: 'unless-stopped'
    pull: yes
    network_mode: host
    env:
      PUID: '1000'
      PGID: '1000'
      VERSION: 'latest'
      PLEX_CLAIM: "{{ plex_claim }}"
    volumes: 
      - "{{ docker_containers_directory }}/plex/config:/config"
      - "{{ media_directory }}/Series:/tv"
      - "{{ media_directory }}/Movies:/movies"
      - "{{ media_directory }}/Movies 4K:/movies-4k"
      