plex_config_volume: "{{ docker_containers_directory }}/plex:/config"
plex_config_volumes:
  - "{{ plex_config_volume }}"
plex_categories_paths: "{{ [ media_directory + '/'] | product(media_directories) | map('join')  }}"
plex_categories_internal_paths: "{{ media_directories | map('lower') }}"
plex_categories_volumes: "{{ plex_categories_paths | zip(plex_categories_internal_paths) | map('join', ':/') }}"
plex_container_volumes: "{{ plex_config_volumes + plex_categories_volumes }}"