---

- name: Create script for updating duck DNS IP
  template:
    src: 'update-duck-dns-ip/script.j2'
    dest: '/opt/scripts/update-duck-dns-ip.sh'
    mode: 0755
    owner: root
    group: root

- name: Create service for updating duck DNS IP
  template:
    src: 'update-duck-dns-ip/service.j2'
    dest: '/etc/systemd/system/update-duck-dns-ip.service'
    mode: 0755
    owner: root
    group: root

- name: Make sure service for updating duck DNS IP is enabled
  service:
    name: 'update-duck-dns-ip.service'
    enabled: yes

- name: Create timer for updating duck DNS IP
  template:
    src: 'update-duck-dns-ip/timer.j2'
    dest: '/etc/systemd/system/update-duck-dns-ip.timer'
    mode: 0755
    owner: root
    group: root

- name: Make sure timer for updating duck DNS IP is enabled and started
  service:
    name: 'update-duck-dns-ip.timer'
    enabled: yes
    state: started