---
- name: Create docker container for Unmanic
  docker_container:
    name: unmanic
    image: josh5/unmanic:latest
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/unmanic/config:/config"
      - "{{ docker_containers_directory }}/unmanic/temp:/tmp/unmanic"
      - "{{ mergerfs_directory }}/downloaded:/library/downloaded"
      - "{{ mergerfs_directory }}/media:/library/media"
    ports:
      - '8888:8888' # UI
    networks:
      - name: services
