---
- name: Create docker container for Radarr
  docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/radarr/config:/config"
      - "{{ mergerfs_directory }}/media/Movies:/movies"
      - "{{ mergerfs_directory }}/downloads:/downloads"
      - "{{ mergerfs_directory }}/configs:/configs"
    ports:
      - '7878:7878'
    networks:
      - name: services

# Enable this on "importing" and "added" hooks
- name: Create script for deleting oldest movies when added new ones
  template:
    src: 'delete-oldest-movie.sh.j2'
    dest: '{{ mergerfs_directory }}/configs/delete-oldest-movie.sh'
    mode: 0755
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Create docker container for Radarr (for 4K movies)
  docker_container:
    name: radarr-4k
    image: lscr.io/linuxserver/radarr
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/radarr-4k/config:/config"
      - "{{ mergerfs_directory }}/media/Movies 4K:/movies"
      - "{{ mergerfs_directory }}/downloads:/downloads"
    ports:
      - '7879:7878'
    networks:
      - name: services