- name: Create docker container for Deluge
  docker_container:
    name: deluge
    image: lscr.io/linuxserver/deluge
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      VERSION: 'docker'
      PLEX_CLAIM: "{{ plex_claim }}"
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/deluge/config:/config"
      - "{{ mergerfs_directory }}/downloads:/downloads"
    ports:
      - '8112:8112'
      - '6881:6881'
      - '6881:6881/udp'
    networks:
      - name: services