---
- name: Create docker container for dashdot
  docker_container:
    name: dashdot
    image: mauricenino/dashdot:latest
    pull: yes
    restart_policy: 'unless-stopped'
    privileged: yes
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
    volumes: 
      - "{{ docker_containers_directory }}/dash/config:/config"
      - "/:/mnt/host:ro"
    ports:
      - '3001:3001'
    networks:
      - name: services

