---
- name: Create docker container for ytdl-sub
  docker_container:
    name: ytdl-sub
    image: ghcr.io/jmbannon/ytdl-sub:latest
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/ytdl-sub/config:/config"
      - "{{ mergerfs_directory }}/media/Series:/tv"
      - "{{ mergerfs_directory }}/media/Movies:/movies"
    network_mode: host
