---
- name: Create docker container for Swag
  docker_container:
    name: swag
    image: lscr.io/linuxserver/swag
    capabilities:
      - NET_ADMIN
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ ntp_timezone }}'
      DUCKDNSTOKEN: '{{ duckdns_token }}'
      URL: '{{ duckdns_domain }}'
      VALIDATION: duckdns
      EMAIL:  '{{ personal_email }}'
    ports:
      - 443:443
      - 80:80
    volumes:
      - "{{ docker_containers_directory }}/swag/config:/config"

- name: Include plex proxy subfolder
  template:
    src: 'plex/subfolder.j2'
    dest: '{{ docker_containers_directory }}/swag/config/nginx/proxy-confs/plex.subfolder.conf'
    mode: 0664
    owner: root
    group: root

- name: Include plex proxy subdomain
  template:
    src: 'plex/subdomain.j2'
    dest: '{{ docker_containers_directory }}/swag/config/nginx/proxy-confs/plex.subdomain.conf'
    mode: 0664
    owner: root
    group: root
  