---
- name: Create docker container for Swag
  docker_container:
    name: swag
    pull: yes
    image: ghcr.io/linuxserver/swag
    capabilities:
      - NET_ADMIN
    restart_policy: 'unless-stopped'
    # https://github.com/ansible-collections/community.docker/issues/70
    default_host_ip: ''
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
      DUCKDNSTOKEN: '{{ duckdns_token }}'
      URL: '{{ duckdns_domain }}'
      VALIDATION: duckdns
      EMAIL:  '{{ personal_email }}'
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - "{{ docker_containers_directory }}/swag/config:/config"
    networks:
      - name: services

- name: Include proxy subfolders configurations
  template:
    src: 'proxy-confs/{{ item }}/subfolder.j2'
    dest: '{{ docker_containers_directory }}/swag/config/nginx/proxy-confs/{{ item }}.subfolder.conf'
    mode: 0664
    owner: root
    group: root
  with_items: '{{ services }}'

- name: Include default site configurations
  template:
    src: 'site-confs/default.j2'
    dest: '{{ docker_containers_directory }}/swag/config/nginx/site-confs/default'
    mode: 0664
    owner: root
    group: root

- name: Include Authelia configuration files
  template:
    src: 'nginx/{{ item }}.j2'
    dest: '{{ docker_containers_directory }}/swag/config/nginx/{{ item }}.conf'
    mode: 0664
    owner: root
    group: root
  with_items:
    - authelia-location
    - authelia-server