---
- name: Create docker container for Home Assistant
  docker_container:
    name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    pull: yes
    restart_policy: 'unless-stopped'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ timezone }}'
    volumes: 
      - "{{ docker_containers_directory }}/homeassistant:/config"
    ports:
      - '8123:8123'
    networks:
      - name: services

